WITH TRIPS AS (

    SELECT 
        RIDE_ID,
        -- RIDEABLE_TYPE,
        
        DATE(TRY_TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
        START_STATIO_ID,
        END_STATION_ID,
        MEMBER_CSUAL,
        
        TIMESTAMPDIFF(second, TRY_TO_TIMESTAMP(STARTED_AT), TRY_TO_TIMESTAMP(ENDED_AT)) AS TIME_DURATION_SECONDS
    FROM {{ ref('stg_bike') }}

    WHERE RIDE_ID != '"BIKEID"' AND RIDE_ID != 'BIKEID'
    LIMIT 10
)

SELECT * FROM TRIPS